import React,{useEffect,useMemo,useState}from'react'
import{BarChart3,CalendarDays,UsersRound,UserRoundCheck,GitCompareArrows,RefreshCcw}from'lucide-react'
import{managerApi}from'../lib/api'
import{localToday,localShiftDays}from'../lib/date'
const presets=[['today','Oggi',0],['7','7 giorni',6],['30','30 giorni',29]]
function maxValue(rows=[]){return Math.max(1,...rows.map(x=>Number(x.value||0)))}
export default function StatisticsPage(){const[preset,setPreset]=useState('7'),[start,setStart]=useState(localShiftDays(-6)),[end,setEnd]=useState(localToday()),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const choose=(key,days)=>{setPreset(key);setEnd(localToday());setStart(localShiftDays(-days))};const load=async()=>{setBusy(true);setError('');try{setData(await managerApi('getStatistics',start,end,preset))}catch(e){setError(e.message)}finally{setBusy(false)}};useEffect(()=>{load()},[start,end,preset]);const totals=data?.totals||{},cmp=data?.comparison||{},same=data?.todayComparison?.atSameTime||{};return <section className="page stats-page" data-testid="manager-statistics"><div className="page-title"><div><div className="eyebrow">Analisi</div><h1>Centro di Controllo</h1><p>Numeri operativi e comportamento delle prenotazioni.</p></div><button className="small-action" onClick={load} disabled={busy}><RefreshCcw className={busy?'spin':''} size={16}/> Aggiorna</button></div>{error&&<div className="editor-error" role="alert">{error}</div>}<div className="stats-toolbar"><div className="filters">{presets.map(([k,l,d])=><button className={preset===k?'active':''} key={k} onClick={()=>choose(k,d)}>{l}</button>)}</div><div className="date-range"><input type="date" value={start} onChange={e=>{setPreset('custom');setStart(e.target.value)}}/><span>→</span><input type="date" value={end} onChange={e=>{setPreset('custom');setEnd(e.target.value)}}/></div></div><div className="stats"><Metric icon={CalendarDays} label="Prenotazioni" value={totals.bookings??'—'} delta={cmp.bookingsDelta}/><Metric icon={UsersRound} label="Coperti" value={totals.covers??'—'} delta={cmp.coversDelta}/><Metric icon={UserRoundCheck} label="Clienti di ritorno" value={totals.returningCustomers??'—'} sub={`${totals.newCustomers??0} nuovi`}/><Metric icon={BarChart3} label="Accettazione motore" value={`${totals.acceptanceRate??0}%`} sub={`${totals.engineDecisions??0} decisioni`}/></div><div className="control-grid"><ChartPanel title="Coperti per fascia" rows={data?.times}/><ChartPanel title="Coperti per sala" rows={data?.rooms}/><ChartPanel title="Fonti prenotazioni" rows={data?.sources}/><ChartPanel title="Stati" rows={data?.statuses}/></div><div className="comparison-strip"><GitCompareArrows size={18}/><div><strong>Confronto con lo stesso momento di 7 giorni fa</strong><span>Prenotazioni: {same.bookings?.current??'—'} vs {same.bookings?.previous??'—'} · Coperti: {same.covers?.current??'—'} vs {same.covers?.previous??'—'}</span></div></div></section>}
function Metric({icon:Icon,label,value,delta,sub}){return <article className="stat metric-card"><Icon size={18}/><strong>{value}</strong><span>{label}</span>{delta!==undefined&&<small className={delta>0?'up':delta<0?'down':''}>{delta>0?'+':''}{delta} vs periodo precedente</small>}{sub&&<small>{sub}</small>}</article>}
function ChartPanel({title,rows=[]}){const max=useMemo(()=>maxValue(rows),[rows]);return <article className="panel mini-chart"><div className="panel-head"><div><span>Distribuzione</span><h2>{title}</h2></div></div><div className="bar-list">{rows.slice(0,8).map((r,i)=><div className="bar-row" key={`${r.label}-${i}`}><div><strong>{r.label}</strong><span>{r.value}</span></div><i><b style={{width:`${Math.max(3,Number(r.value||0)/max*100)}%`}}/></i></div>)}{!rows.length&&<div className="empty">Nessun dato nel periodo.</div>}</div></article>}
